/*
  Login types constant defined here
*/
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const IS_LOADING = 'IS_LOADING'
export const LOG_OUT = 'LOG_OUT'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SHOW_CONFIRM = 'SHOW_CONFIRM'
export const SEND_USER = 'SEND_USER'

// Signup
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const CONFIRM_USER = 'CONFIRM_USER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const SEND_FORGOT_PASSWORD_TOKEN_SUCCESS =
	'SEND_FORGOT_PASSWORD_TOKEN_SUCCESS'
export const SEND_FORGOT_PASSWORD_TOKEN_FAILURE =
	'SEND_FORGOT_PASSWORD_TOKEN_FAILURE'

// User
export const COGNITO_USER_REMOVE = 'COGNITO_USER_REMOVE'
export const COGNITO_USER_ADD = 'COGNITO_USER_ADD'

//Payment
export const PAYMENT_SUCCESSFULL = 'PAYMENT_SUCCESSFULL'
export const PAYMENT_FAILED = 'PAYMENT_FAILED'

// Business Create
export const BUSINESS_FETCHED = 'BUSINESS_FETCHED'
export const BUSINESS_NOT_FETCHED = 'BUSINESS_NOT_FETCHED'
export const BUSINESS_UPDATE = 'BUSINESS_UPDATE'
export const BUILDING_DELETE = 'BUILDING_DELETE'
export const BUILDING_ADDED = 'BUILDING_ADDED'

// Business Data
export const BUSINESS_LIST = 'BUSINESS_LIST'
export const CURRENT_BUSINESS_LIST = 'CURRENT_BUSINESS_LIST'
export const GLOBAL_MESSAGE = 'GLOBAL_MESSAGE'

// Transaction
export const TRANSACTION_ADD = 'TRANSACTION_ADD'
export const TRANSACTION_LOAD = 'TRANSACTION_LOAD'
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE'

// Employee
export const EMPLOYEE_ADD = 'EMPLOYEE_ADD'
export const EMPLOYEE_LOAD = 'EMPLOYEE_LOAD'
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'

// Attendance
export const ATTENDANCE_ADD = 'ATTENDANCE_ADD'
export const ATTENDANCE_LOAD='ATTENDANCE_LOAD'
export const ATTENDANCE_DELETE = 'ATTENDANCE_DELETE'